### PR TITLE
[WIP] Carnivores 

### PR DESCRIPTION
**Pull request by PRabahy**
I thought this would be fun to add. I haven't really had time to fully flesh out the idea, but it runs without crashing. I have verified that both the meat (new) and food (old) get eaten.

I'm mostly just looking for feedback if people like this idea.

### CODE REVIEW

**Comment by SirSKillz** [comment]
Can you explain what happens to the meat over time? I didn't notice some kind of "rotting" where it will slowly disappear. Also, from an efficiency standpoint, adding meat to each tile is going to slow down each iteration quite a bit.

I think this is a necessary item as eating other creatures is definitely a part of survival and evolution. Also, having predators and prey could create interesting changes in behavior to avoid being harmed. This could create complications, but I think it would be well worth it overall to create a more realistic evolution simulator.

**Comment by PRabahy** [comment]
For now the meat just sits there forever. I have some longer term ideas where the fertility of each tile will go down over time. When an animal dies on that tile, it would drop meat. Over time, the meat would decay and increase the fertility of the tile.

I tried messing around with this a bit yesterday, but I must have done something wrong because the tiles kept turning to water when a creature died there.

**Comment by SirSKillz** [comment]
I think the fertility idea would be very interesting, but maybe it would be better to get the meat to work first? Simulation of fertility for each tile is going to be painful for performance, which I would really like to see improve before we add too many new things. Perhaps add fertility as an option that we can choose whether or not to have in the simulation, but add the meat decay as an overall idea?

**Comment by SirSKillz** [comment]
I was looking around to see why your fertility thing wasn't working and turning tiles to water and found this in Tile.pde under public void iterate()

if (fertility > 1) { // This means the tile is water.
        foodLevel = 0;
      } else {
        if (growthChange > 0) { // Food is growing. Exponentially approach maxGrowthLevel.
          if (foodLevel < maxGrowthLevel) {
            double newDistToMax = (maxGrowthLevel-foodLevel)*Math.pow(2.71828182846, -growthChange*fertility*FOOD_GROWTH_RATE);
            double foodGrowthAmount = (maxGrowthLevel-newDistToMax)-foodLevel;
            addFood(foodGrowthAmount, climateType, false);
          }
        } else { // Food is dying off. Exponentially approach 0.
          removeFood(foodLevel-foodLevel*Math.pow(2.71828182846, growthChange*FOOD_GROWTH_RATE), false);
        }
        /*if (growableTime > 0) {
         if (foodLevel < maxGrowthLevel) {
         double foodGrowthAmount = (maxGrowthLevel-foodLevel)*fertility*FOOD_GROWTH_RATE*timeStep*growableTime;
         addFood(foodGrowthAmount, climateType);
         }
         } else {
         foodLevel += maxGrowthLevel*foodLevel*FOOD_GROWTH_RATE*timeStep*growableTime;
         }*/
      }
      foodLevel = Math.max(foodLevel, 0);
      lastUpdateTime = updateTime;
    }

I bet that is why the tiles were turning to water on you. Enjoy ;-)

**Comment by SirSKillz** [comment]
Just wanted to make sure you got this, incase you don't have notifications on @PRabahy

**Comment by PRabahy** [comment]
Yep, got the message, but still haven't had time to figure it out. I had already modified that code, but I think must have messed something up. If I'm reading it correctly now:
0.001 = Very low fertility and therefore slow growth.
0.999 = Very high fertility and therefore fast growth.
1.000 = Water
1.234 = Water

**Comment by PRabahy** [comment]
Closing because I was lazy developed directly off of master. I'll reopen this when I fix the bugs put it on a proper branch.

**Pull request closed without merging**
