### PR TITLE
Board.pde

### PR DESCRIPTION
**Pull request by israelraizer**
changes made to implement the Fast Draw option to the useless button...

### CODE REVIEW

**Comment by CrazyPython** [comment]
dammit, win/unix newlines. Just use unix newlines from now on.

**Comment by Cody-Soultz** [comment]
if you use the CLI of git for windows it reverts line endings to the original line endings when commenting your code.

**Comment by mbertheau** [comment]
@israelraizer the net changes in this PR (without the whitespace/line ending changes) don't contain to make `fastDraw` actually do anything: https://github.com/evolvio/evolv.io/pull/18/files?w=0

**Comment by mbertheau** [comment]
@israelraizer thank you for your contribution and you efforts in handling git and GitHub. Do you want us to make the necessary changes, or do you want to take this opportunity and try it yourself? In the second case I'd recommend downloading the GitHub Desktop application from desktop.github.com and follow the instructions there. Best to make a new clone for now. You can do that in the app.

**Comment by mbertheau** [comment]
I suggest having the button labeled "Hide world" and "Show world" respectively, and the variable named accordingly. This should be clearer than "fast draw".

Preferably but optionally, when the world is hidden, instead of the world, draw a "world hidden" sign, or a "creatures continue to evolve" sign or something :)

**Comment by mbertheau** [comment]
This PR was closed in the process of #38 happening. #38 shouldn't have happened though (see there). Please create a new PR with your branch. There should be a button "Create pull request") next to the branch `patch-1` here: https://github.com/israelraizer/evolv.io/branches

Sorry for this happening.

**Comment by YoYoYonnY** [comment]
@mbertheau I'm pretty sure this pull request was already closed before the force push.

**Comment by YoYoYonnY** [comment]
@mbertheau The only pull requests that I know were open are #36 and #37. I checked before I pushed.

**Comment by mbertheau** [comment]
@YoYoYonnY you closed it an hour ago without comment. I assumed that was in relation to #38. Sorry if I'm mistaken. In any case, no PR should be closed without an explanation.

**Pull request closed without merging**
