### PR TITLE
Created Config file

### PR DESCRIPTION
**Pull request by SirSKillz**
The file contains most of the Final variables, and is organized for each
class. They are in order of which they come in the class.

This is for so we can have a place to discuss the Config, please don't merge until this is in a more finished state.

### CODE REVIEW

**Comment by SirSKillz** [comment]
Most of the descriptions were me guessing at what each did. Any that still have "Info of what this does" is something that I had no good guess. I recommend going through them and editing the descriptions so be more accurate to what they actually control in the program. Perhaps also a range descriptor so users can understand what maxima/ minima there are for each config, if applicable?

**Comment by NateUniAccount** [comment]
Can I suggest the file is just another java class. Otherwise we'd need a config reader class as well which has to parse the config file. With just another java class we could just reference the variables directly.

**Comment by SirSKillz** [comment]
This could be a good idea as well, as we are editing the code, but I'm sure there are also people who enjoy the program with little to no programming knowledge. We could have the config file that sets the values in a java class if you want, but I think having an actual config file would be good for people who want to just see what this is about.

**Comment by SirSKillz** [comment]
Would that be a better bridge for you? @NateUniAccount

**Comment by NateUniAccount** [comment]
Closing this PR as the work has been moved into the configuration_java_file branch

**Pull request closed without merging**
