### PR TITLE
Random seed

### PR DESCRIPTION
**Pull request by Punchkin**
The seed is being generated randomly and is shown in the top right corner below the season

//Reentered :)

### CODE REVIEW

**Comment by Punchkin** [comment]
Good point. I thought showing it would be better, so the user can save some
of the cooler seeds.

Am 11.10.2016 21:58 schrieb "NateUniAccount" <notifications@github.com>:

**Comment by NateUniAccount** [comment]
Yeah that's a nice idea, are you thinking the user could set the seed in the code rather than through the UI?

**Comment by Punchkin** [comment]
The user can't set the seed in the ui. The user has to set it in the code.

Am 11.10.2016 22:47 schrieb "NateUniAccount" <notifications@github.com>:

**Comment by mbertheau** [comment]
I think having a random seed every time the app is started is a nice addition, since beginners get different results each time, which allows them to see the breadth of the simulation without first having to change the code.

The ability to retry specific seeds is an advanced use, where it's ok for now that you have to change the code to do that. Later we might want to add UI to set simulation parameters including the seed.

Thank you for your contribution!

**Comment by IHaveADrone** [comment]
side note:
Isn't using the same seed effectively only keeping the map the same?
Aren't the creature's evolution so chaotic that the exact frame you switch over to brain control changes everything?

**Pull request merged**
