### PR TITLE
Updated with How To Run

### PR DESCRIPTION
**Pull request by AutumnRayne**
Just integrating Issue #4

### CODE REVIEW

**Comment by CrazyPython** [comment]
```
1. -> 1)
2. -> 2)
etc.
```

**Comment by mbertheau** [comment]
@AutumnRayne if you click on the "Files" tab in this PR, and then on the button "View" for README.md you can see how the file will be rendered.

Also the GitHub Desktop application https://desktop.github.com/ might be helpful in creating and changing PRs.

@CrazyPython I believe you can make all numbers 1; the renderer will number the items consecutively then.

Thank you both for your contributions!

**Comment by CrazyPython** [comment]
@mbertheau markdown is supposed to be readable in plain text too. it also makes it easier to edit. Just use the normal `1 -4`.

**Comment by AutumnRayne** [comment]
Okay, so now that I know how to change the formatting... how do I edit the PR? Do I have to make a new one?

**Comment by Cody-Soultz** [comment]
No I just learned that all you need to do is commit your change to the AutumnRayne:patch-2 branch and it will add itself

**Pull request closed without merging**
