### PR TITLE
Change CreatureMinimum to SpawnChance.

### PR DESCRIPTION
**Pull request by PRabahy**
This will allow more brain diversity once the population has stabilized.

### CODE REVIEW

**Comment by NateUniAccount** [comment]
Would you mind putting it onto a branch in the evolvio repo please? Its easier to pull the branch that way

**Comment by PRabahy** [comment]
Sure, but most other projects I have been involved in encourage people to do work in their own forks, then make pull requests into the main fork. That way everybody is on an even playing field. Otherwise, only people that have been added to the project can push to the main fork and everybody else is stuck doing something non-standard. If you want to check out somebody else's work, you can either add their remote to your clone, or do a fully qualified pull (git pull https://github.com/PRabahy/evolv.io.git feature/SpawnChance).

Either way no big deal and I'll push my work to main for now.

**Comment by NateUniAccount** [comment]
Thanks for putting it in this repo! Will have to get round to figuring out adding remotes etc. on Windows later!
Not really sure what to think about this really, it checks whether to add another creature every iteration, so there'll be no upper limit on how many creatures there are. The maintain creature minimum method only kicked in if the number of creatures got too low, but this happens regardless of how many there are.
It's basically manual reproduction instead of allowing the creatures to evolve to choose it themselves. Think it's better to keep it as it was, that's my 2 cents.
Anyone else have thoughts?

**Comment by PRabahy** [comment]
My logic behind this change is that I was seeing several maps that were split into 2 or 3 islands. One island would have sustainable evolution first then the remaining islands would stay empty forever. In addition, this allow completely new brains to try competing against existing brains. In some simulations, it appears that 1 or 2 general brain's end up taking over the entire map.

I wouldn't mind making an enhancement that the possibility of spawning a new random creature would be inversely proportional to the number of existing creatures. For example, if there was only 5 creatures, it would be very likely to spawn a new creature, but if there were 500 creatures, it would be very unlikely to spawn. Does that sounds better?

**Comment by NateUniAccount** [comment]
Yeah that sounds good! What do you think about having a limit as well so if the population was say 50 (?) or more no new creatures would be added?

**Comment by PRabahy** [comment]
I don't think adding a limit on the population is a good idea. One of my main points behind this is to try to give each island a chance at life. If one island ends up with 50 creatures, the other island will likely remain barren forever.

**Comment by NateUniAccount** [comment]
Ah sorry about the misunderstanding...I meant if there were already say 50 creatures, the chance of spawning a new creature using this method would be zero. Creatures will always be able to birth new creatures if they want.

**Comment by PRabahy** [comment]
No, I believe I understood you. When creatures give birth, it happens right next to the creature giving birth. I want something that will happen at essentially a random location.

Maybe I could make 2 parameters. One that is the general spawn rate, and another that is the population weight. For you, you could have the population weight set high so that once there "enough" creature, the odds of a random one spawning would be effectively 0, and I could set is low-ish so there is still a decent chance.

**Comment by NateUniAccount** [comment]
Been thinking about it a lot and am liking how you have it now more and more so no worries about changing it unless you want to

**Pull request merged**
