### PR TITLE
Updating style and adding license

### PR DESCRIPTION
**Pull request by YoYoYonnY**
I've added the MIT license as a temporary placeholder license. We might want to change this.

### CODE REVIEW

**Comment by mbertheau** [comment]
License decision is up to carykh, I asked him about it here: https://www.youtube.com/watch?v=OLnv8QaEDL0&lc=z123d3apirany5iz304cflmq3qfdw30houc0k.1475397522762953 I realize that we're in muddy license waters until then; nevertheless I'd refrain from choosing a license without carykh's consent.

I added the three other commits to master.

**Comment by mbertheau** [comment]
Also thanks for resurrecting `settings()` :)

**Comment by YoYoYonnY** [comment]
I see the pull request is still open, but the commits are already pulled. Not sure how that happened, but it seems like a problem with GitHub. Closing.

**Comment by mbertheau** [comment]
@YoYoYonnY I cherry-picked three of your commits, but not the license one. That's why the PR was still open.

**Comment by YoYoYonnY** [comment]
@mbertheau Ah, I see. I'm pretty sure it would've been possible to do the same by performing a rebase, but this works too.

**Pull request closed without merging**
