### PR TITLE
Feature/eclipse

### PR DESCRIPTION
**Pull request by PRabahy**
This PR is the bulk of the work needed to port evolve.io from Processing to Eclipse. Everything appears to work to me.

### CODE REVIEW

**Comment by PRabahy** [comment]
I thought this would get linked automatically... This is for issue #70.

**Comment by PRabahy** [comment]
I intentionally didn't want to get into any style wars about indentation, brackets, line length, etc. so I left everything the default in Eclipse and did ctrl+shift+f in each file before saving it. I am of a very strong opinion that trying to fight the default will only frustrate people. I don't like several of the default behaviors, but it is not worth it to me to try to modify them.

**Comment by PRabahy** [comment]
I wonder why the included version of core.jar didn't work for you. Which operating system are you using? I checked and processing is in the Maven repositories, so I might convert the project to Maven or Gradle so that we don't need to include the actual jar in this git repository. I believe that Eclipse comes with support for Maven by default, so I'll probably end up using that.

**Comment by kodomazer** [comment]
I'm  using Windows, and 64-bit eclipse.  I figured that's why it didn't work.

**Comment by PRabahy** [comment]
Strange, that's the same system that I am using.

**Comment by SirSKillz** [comment]
Also, for those who are new to Eclipse (as I am), the way you run the simulation is by right clicking on the project folder in the Eclipse "Package Explorer" (as in the folder containing the src), click on "Run As" about 3/4th down the list, and the click "2 Java Application."

Or, if you're feeling lazy you can use hotkeys "Alt+Shift+X" and then "J" when the menu comes up in the bottom right.

**Comment by PRabahy** [comment]
@kodomazer and @SirSKillz can you retry it now that the dependency is controlled by Maven. In theory, Maven should pull whichever jar(s) you need to work with your system.

**Comment by SirSKillz** [comment]
I have no idea how to use Maven, could you explain it to me? @PRabahy

**Comment by SirSKillz** [comment]
After converting to Maven, the project did work. Not sure if this is a good fix as it is system dependent, but the error is gone so I am comfortable moving forward.

**Comment by kodomazer** [comment]
I'm going to test it out and then Squash and Merge if all goes well.

**Comment by kodomazer** [comment]
Everything worked out okay.

For future reference, is there a better way to test the commits, than to download a zip of the commit in question and pop it into a directory and test it from there?

**Comment by PRabahy** [comment]
@SirSKillz There is a Maven plugin built right into Eclipse by default, so you don't really need to know anything about using Maven. All you have to do is to click the green play button to start it (looks like you already figured this out).

@kodomazer Yep, there is an easier way to test it. Right next to the "Squash and merge" button it says "You can also open this in GitHub Desktop or view command line instructions." Just click either of those links to use git to pull down the pull request to test.

**Comment by PRabahy** [comment]
@SirSKillz "Not sure if this is a good fix as it is system dependent, but the error is gone so I am comfortable moving forward." What do you mean? The whole idea about going to Maven is that it is not system dependent. If somebody comes along and wants to use IntelliJ, now that it is a Maven project it is much easier for them to import. If a person doesn't want to use an IDE at all, they will have to install the mvn command line utility, but that is available for Windows, Linux, and Mac.

**Pull request merged**
