### PR TITLE
allows creatures to mutate their preference for living on land or water

### PR DESCRIPTION
**Pull request by SerayaEryn**
Creatures now may develop the ability to live on water.

- each creature has a preference to live on land and a preference to live on water
- based on the preference creature is able to eat more efficient on land or water
- there is a chance to randomly mutate the preference to live on land/water

### CODE REVIEW

**Comment by NateUniAccount** [comment]
A few things have been cleaned that maybe would be better put into a separate pr

**Comment by NateUniAccount** [comment]
The mutate() method and MUTATION_CHANCE field could be named to say they're to do with water/land preference

**Comment by mbertheau** [comment]
I think, from an evolutionary standpoint, a water/land preference isn't something encoded in genes, but would rather arise from more basic variables. In the code in this PR, the water/land preference seems to have an effect in two places: when eating on land/water and when moving there. I think these could evolve directly and separately.

Also this PR needs to be rebased on the current master, since there are conflicts.

**Comment by SerayaEryn** [comment]
I think evolve eating and moving on land/water together is detailed enough for our simulation. 

But I agree in reality this would be encoded by a great number of genes.

**Comment by mbertheau** [comment]
Hmm, after this PR was closed in the process of #38 happening, I reverted #38 and still I cannot seem to re-open this PR, sorry. I could create a new one though with the same changes: #39.

**Pull request closed without merging**
