### PR TITLE
Changed if-else statements for the buttons to a switch statement

### PR DESCRIPTION
**Pull request by SirSKillz**
This makes it easier to read and to edit what each button does. I see performance gains most of the time, but I haven't checked it with Proccessing.

### CODE REVIEW

**Comment by SirSKillz** [comment]
I feel like I did this incorrectly... Why did it show the code clean up as well, despite not actually editing any of those files again?

**Comment by mbertheau** [comment]
How did you create the new commits? Do you use git on the command line?

I see that the this PR is for merging your master into evolvio's master. The usual way is to create a branch for each PR.

You can do the following, if you use git on the command line:

```
# check that you have committed all changes - git status should say "working directory clean"
git status

# check out the evolvio master branch, which contains the code cleanup changes, but not the if/switch changes
git checkout evolvio/master

# create a new branch
git branch change-if-to-switch

# make the new branch the active branch
git checkout change-if-to-switch

# you could also have done both in one go like this:
# git checkout -b change-if-to-switch

# get the commits with your changes. I got the commit ids from the commit list above.
git cherry-pick d6526d9
git cherry-pick f7027f9
```

Now push the `change-if-to-switch` branch to github and change this PR's "from" branch to the `change-if-to-switch` branch. This should update this PR to have only the last two commits.

We can see about merging these together later (No need for the "Update EvolvioColor.pde" commit to be separate).

**Comment by SirSKillz** [comment]
Hahaha! That's what I forgot to do. Whoops! I'll take care of it later tonight.

**Comment by SirSKillz** [comment]
Apparently I screwed up at some point, because cherry-pick doesn't want to take d6526d9. 

"error: could not apply d6526d9... Changed if-else statements for the buttons to a switch statement
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>"

I'm completely unfamiliar with the Git Shell, so I have no idea how to go about fixing this. Could you help me out, or do you think merging anyway would be easier? I don't believe anyone has updated the Master since my last commit, so it shouldn't cause too many problems.

**Comment by mbertheau** [comment]
I created a new PR #54 with your code. I can't update this PR since it's from your repository. You can go ahead and merge #54 if the CI shows no errors :)

Closing this PR, since #54 replaced it.

**Pull request closed without merging**
