### PR TITLE
Set user control to false

### PR DESCRIPTION
**Pull request by Punchkin**

### CODE REVIEW

**Comment by YoYoYonnY** [comment]
See #38

**Comment by mbertheau** [comment]
@Punchkin I'm sorry that this has been (according to your public github profile) your first experience with collaboration on open source projects on GitHub.

If I understand GitHub correctly you have removed your fork that contained the branch for this PR. I will see what I can do about that without you having to re-do the work you put into this PR.

**Comment by Punchkin** [comment]
Oh yeah. I accidently (more or less) deleted it. I'll reenter it as soon as
I can (if I'm allowed)

Am 11.10.2016 18:26 schrieb "Markus Bertheau" <notifications@github.com>:

**Comment by mbertheau** [comment]
We cannot stop you and it fact encourage you to do it :)

**Comment by Punchkin** [comment]
Okay. Btw: yes, i'm new to github :D

Am 11.10.2016 18:31 schrieb "Markus Bertheau" <notifications@github.com>:

**Pull request closed without merging**
