### PR TITLE
Fixes for Issue 8

### PR DESCRIPTION
**Pull request by AutumnRayne**
Applied the redmouth fix to the body hue, as well.

Also fixed the neural network so that it's not dead after generation.

Also, I only changed 4 lines, but the entire file is listed as having been deleted and readded? Is that supposed to happen?

### CODE REVIEW

**Comment by IHaveADrone** [comment]
It looks like a glitch on git's end as far as I can tell.   Definitely not supposed to happen.

**Comment by mbertheau** [comment]
The entire file is listed as changed because the line endings have changed, presumably from unix style (`\n`) to windows style (`\r\n`). You can see the actual diff by appending `?w=0` to the url: https://github.com/evolvio/evolv.io/pull/10/files?w=0 This will ignore whitespace changes.

You can try to fix the PR yourself or I'll incorporate the relevant changes myself, no problem with that also :)

**Comment by AutumnRayne** [comment]
Seeing as I can't even figure out how to edit a commit, I'll leave it to you, haha. I'm brand new at using Github, and I'm not a very experienced programmer to boot.

**Comment by CrazyPython** [comment]
@AutumnRayne You can't really edit a commit - not in a meaningful or recommended way anyway. Instead,

1. add a new commit on top of your old one @ https://github.com/AutumnRayne/evolv.io/tree/patch-1. This means that commit will also be added to this PR. You can use the inline edit button there.
2. to make it appear as one commit in the history, have the merger perform a squash & merge.

(also google it next time :))

**Comment by AutumnRayne** [comment]
Good stuff, thanks Crazy!

mbertheau, I can't seem to find any option in the editors to change the line endings. Is it just a matter that they change because I accessed the file from a Windows computer? If not, how did I change them, and how can I avoid doing that in the future? (as far as I know, I literally just opened the edit file option, made the changes, and hit commit. I also think I might have copied a few of the lines from a text file? Is that a problem? Other than that, I can't think of any outside factor)

**Comment by YoYoYonnY** [comment]
Changes have been merged. Closing.

**Comment by mbertheau** [comment]
@AutumnRayne @CrazyPython you can edit a commit and in this case it would have made perfect sense to do so. However it's not intuitively obvious how to do that.

It's also not obvious how to fix the line endings. You also didn't mess them up, they were messed up before and your editor tried to make the best of it, which is hard when different types of line endings are mixed in the same file. However, @YoYoYonnY has since fixed all line ending issues such that they shouldn't be an issue again.

Thank you all for your efforts!

**Pull request merged**
