### PR TITLE
Brain Separated

### PR DESCRIPTION
**Pull request by kodomazer**
Moved the Brain code into its own class.

This time it didn't break anything.  I don't think...
I'm seeing population increases, so I think brain info is being passed along properly unlike #57

### CODE REVIEW

**Comment by PRabahy** [comment]
So whats the difference between this PR and the last one? I glanced at them and they look pretty much the same. I'm guessing there was just an important line or 2 of code that was missed the first time.

**Comment by kodomazer** [comment]
In the last one I passed in just the other parents and then added the current brain to the list, and I guess it had some issues with that.  So this time I just grabbed the code and added a ".brain" to get the brain of the creature selected.  This'll bring the code out for now and we can optimize and change it in the future.

**Comment by PRabahy** [comment]
Reviewed the code, and did some brief testing on my machine. LGTM.

**Comment by SirSKillz** [comment]
Is Brain not complete, or can we delete the branch? @kodomazer

**Pull request merged**
