### PR TITLE
Implemented aging of Creatures - Metabolism is increasing with age.

### PR DESCRIPTION
**Pull request by pilger15**
This was implemented to incentivise reproduction.
Since reproduction is very expensive in terms of energy usage, creatures that would not reproduce had a natural advantage. Furthermore those creatures would not help the evolutionary process.
By adding ageing, "species" that do not reproduce will vanish.

### CODE REVIEW

**Comment by mbertheau** [comment]
@pilger15 Thanks! Can you clean up the PR so that there are no missing newlines and no empty lines added? See the "Files changed" tab on the top.

**Comment by PRabahy** [comment]
@mbertheau The Processing IDE automatically removes the blank line at the end of files, so I don't see much advantage in fighting that.

**Comment by pilger15** [comment]
OK i changed it anyways. Cheers ;)

**Comment by mbertheau** [comment]
@PRabahy Hmm, yeah, I agree, it'd be way too much of a hassle for people who do use the IDE.

**Pull request merged**
