### PR TITLE
Pr/69

### PR DESCRIPTION
**Pull request by SirSKillz**
Updated @PRabahy pull request #69 to the current build

### CODE REVIEW

**Comment by PRabahy** [comment]
Why? The other PR didn't have any merge conflicts. Just because a PR isn't based off the tip of master doesn't hurt anything.

Also, if there is a reason to update a PR, usually just make a comment in the first. It can get really confusing if you have multiple copies of the same PR floating around.

**Comment by SirSKillz** [comment]
I was in a hurry and that was faster for me. Sorry about that. I wasn't sure if there were any issues from the master, so I wanted to be safe with that, which is why I asked you to look over it.

**Comment by PRabahy** [comment]
Sounds like you were just using this for speed, so I'm going to close it out. https://help.github.com/articles/checking-out-pull-requests-locally/ gives some tips for checking out the code from a pull request so that you can make sure that it works as expected.

**Comment by SirSKillz** [comment]
Sweet, thanks.

**Pull request closed without merging**
