### PR TITLE
Prepopulate tiles with food.

### PR DESCRIPTION
**Pull request by PRabahy**
Removes a hardcoded 0 and eliminates an artificial famine when the simulation first starts.

### CODE REVIEW

**Comment by SirSKillz** [comment]
I updated your pull request to contain the new Brain. #75

**Comment by PRabahy** [comment]
@SirSKillz Do you like the change and think it should be merged?

**Comment by SirSKillz** [comment]
Yeah, I do. It is strange that the program starts with very little food

**Comment by PRabahy** [comment]
It was strange before or after this change? Before it was hardcoded to 0, so there was nothing strange (from the code's point of view) about starting with very little food. After the change, it doesn't start with the full amount of food, but at least its more than nothing.

**Comment by SirSKillz** [comment]
I just meant that from the perspective of a habitable environment, it is strange that there would be next to no food in the beginning. Your change is an appreciated update.

**Pull request merged**
