### PR TITLE
Changed to be compatible with all screen sizes

### PR DESCRIPTION
**Pull request by Cody-Soultz**
Changed to be compatible with all screen sizes however the right side needs to be in a scroll pane or needs to be scaled based on height of window.

### CODE REVIEW

**Comment by CrazyPython** [comment]
@Cody-Soultz Why make a new PR? Why not just add some more commits on top of the old one?

**Comment by Cody-Soultz** [comment]
I was not sure how to do that...sorry. I should have looked into how to do that.

**Comment by Cody-Soultz** [comment]
That was my first ever pull request to an external git project. In the past I have only done pull request to my own repo's where I had more than one person working with me

**Comment by CrazyPython** [comment]
@Cody-Soultz OK, lemme teach ya! It is simple: add more commits on top of cody-shultz/master. They will automatically be integrated on top - a pull request is just a request to merge your branch with the official branch.

**Comment by CrazyPython** [comment]
Close #15, reopen #9.

**Comment by CrazyPython** [comment]
If you see [here](https://github.com/evolvio/evolv.io/pull/15/files), your changes are already there in the old PR.

**Comment by Cody-Soultz** [comment]
Oh. That is super simple. Should I close this one and reopen the old PR?

**Comment by Cody-Soultz** [comment]
Oh you already did that nice!

**Comment by CrazyPython** [comment]
@Cody-Soultz Close this one and reopen the old one

> Oh you already did that nice!

huh?

**Comment by Cody-Soultz** [comment]
@CrazyPython So in theory for my pull requests I should branch off of my master so that I could keep working on other things while waiting for the PR to be reviewed

**Comment by Cody-Soultz** [comment]
I had thought when you said:

> Close #15, reopen #9.

That you had done that, but I see that I will reopen the other one and close this one

**Comment by CrazyPython** [comment]
@Cody-Soultz Yes. See the [tqdm project](https://github.com/tqdm/tqdm) for a practical example.

**Pull request closed without merging**
